NUMPY ARE NOT FLEXIBLE(HOMOGENEOUS DATA) AND FAST THEN LIST

In [1]:
#INSTALLATION
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


we can use time module
#import time
start = time.time()
end = time.time()
print(f"total time {end-start}})

In [ ]:
#memory
import sys
.getsizeof(list)*list(length)

CREATION OF NUMPY ARRAYS

In [6]:
import numpy as np
#creation from list
arr = np.array([1,2,3,"4"])
print(arr,type(arr))
print(arr.dtype)

['1' '2' '3' '4'] <class 'numpy.ndarray'>
<U21


In [40]:
#2-dimensional data
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.shape)
print(arr2.size)#gives you total elements
print(arr2[2][0])#accessing elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
7


In [16]:
z = np.zeros((2,3))
print(z)
o = np.ones((2,3))
print(o)
i = np.eye(3)
print(i)
r = np.arange(0,10)#similar to range(start,stop,step)
print(r)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]


Different methods
1.type() - to find the type of array
2.dtype -to fine data type of data
5.ndim-to get dimention of data
3.shape - gives you rows and columns
4.size - gives you total elements

In [21]:
arr3 = np.full((3,2),100)
print(arr3)
lin = np.linspace(1,100,4)# will create lineraly spaced array
print(lin)

[[100 100]
 [100 100]
 [100 100]]
[  1.  34.  67. 100.]


In [25]:
#in order to change the data type of data
# we use astype() method to convert data type of data in array
#below is the syantax
float_arr = arr3.astype(np.float64)
print(float_arr)


[[100. 100.]
 [100. 100.]
 [100. 100.]]


DATA manipluation techniques
they always return an another array 

In [30]:
#compatability matters more for reshaping
print(r.reshape(2,5))
print(r)
print(r.transpose())
print(r.T)#use T for transpose method

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Operation on numpy 
1.reshape
2.transpose(T)
3.indexing
4.slicing
5.fancy and boolean indexing


In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[2])




3
